resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: pr-source
    type: pull-request
    source:
      repository: michaelhedrick/concourse
      access_token: 694dd591ba34d3db741b626c2e784a045cb6ead9

jobs:
  - name: cpp-check-pr
    plan:
      - get: pr-source
        trigger: true
      - task: run-cpp-check
        file: cpp-check.sh
        on_success:
          put: pr-source
          resource: pr-source
          params:
            path: concourse
            status: success
            context: cpp-check-pr
        on_failure:
          put: source
          resource: pr-source
          params:
            path: concourse
            status: failure
            context: cpp-check-pr

