resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: jtarchie/pr

resources:
  - name: pr-source
    type: pull-request
    source:
      repo: michaelhedrick/concourse
      access-token: 9b9c31e4cc1c2a3ccfff613b8862f8fc9c4aea07
      uri: https://github.com/michaelhedrick/concourse

jobs:
  - name: cpp-check-pr
    plan:
      - get: source
        resource: pr-source
        trigger: true
      - task: run-cpp-check
        file: cpp-check.yaml
        on_success:
          put: source
          resource: pr-source
          params:
            path: concourse
            status: success
            context: cpp-check-pr
        on_failure:
          put: source
          resource: pr-source
          params:
            path: concourse
            status: failure
            context: cpp-check-pr

